import type { NextPage } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import MainTag from "@/components/MainTag";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainTag title="about" />
    </>
  );
};

export default Home;
