import type { NextPage } from "next";
import Head from "next/head";
import MainTag from "@/components/MainTag";
import Header from "@/components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainTag title="about" />
    </>
  );
};

export default Home;
